[package]
name = "git-remote-utils"
version = "0.1.0"
edition = "2021"
resolver = "2"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
description = "Git utilities for remote login environment"
repository = "https://github.com/gifnksm/git-remote-utils"
license = "MIT or Apache-2.0"

[dependencies]
